<a href="https://colab.research.google.com/github/AbhijeetRPatil/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


## Pytorch deep learning fundamentals notebook


In [5]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [7]:
## Introduction to Tensors
## Creating tensors
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# Get tensor back as Python item
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [21]:
ext = torch.tensor([[[1,3,5], [4,5,6], [7,8,9], [5,6,7],
                     [2,3,4], [4,5,5], [5,6,7], [4,5,6]]])
ext
ext.ndim
ext.shape

torch.Size([1, 8, 3])

## Random tensors
Random rensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

```start with random numbers -> look at the data -> update the random numbers -> look at the data -> output```

In [22]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.3039, 0.0931, 0.5617, 0.3397],
        [0.1956, 0.1939, 0.6500, 0.0918],
        [0.7533, 0.5147, 0.4857, 0.0108]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.9637, 0.1224, 0.5776, 0.8189],
         [0.6431, 0.8568, 0.7116, 0.4506],
         [0.1611, 0.1181, 0.8176, 0.2818]]])

In [25]:
random_tensor.ndim

3

In [26]:
random_tensor=torch.rand(2,3,4)
random_tensor

tensor([[[0.0435, 0.1463, 0.1801, 0.7320],
         [0.1681, 0.6294, 0.6706, 0.6817],
         [0.8780, 0.1295, 0.1218, 0.7777]],

        [[0.1849, 0.7879, 0.7500, 0.4838],
         [0.5757, 0.4473, 0.5700, 0.7200],
         [0.7130, 0.0622, 0.1143, 0.8054]]])

In [27]:
random_tensor.ndim

3

In [28]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [29]:
torch.rand(size=(3,3))

tensor([[0.7330, 0.5717, 0.5963],
        [0.5748, 0.4567, 0.3053],
        [0.3383, 0.2579, 0.6061]])

Zeros and ones

In [30]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [33]:
# Use torch.range()
torch.range(0,10,1)

/tmp/ipython-input-33-3554855963.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10,1)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
torch.__version__

'2.6.0+cu124'

In [35]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
# Creating tensors like
one_to_ten_like = torch.ones_like(input=one_to_ten)
one_to_ten_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor data types

Precision in computing
Note: Tensor dataypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [38]:
# Floar 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on ## cpu, cuda
                               requires_grad=False) # wheather on not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [39]:
float_32_tensor.dtype

torch.float32

In [40]:
# When tensor not in same data type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [42]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32) # torch.long or torch.int16 or other
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [43]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [44]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7898, 0.7117, 0.8518, 0.4933],
        [0.1038, 0.5691, 0.7230, 0.2123],
        [0.2096, 0.2871, 0.9273, 0.4491]])

In [45]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7898, 0.7117, 0.8518, 0.4933],
        [0.1038, 0.5691, 0.7230, 0.2123],
        [0.2096, 0.2871, 0.9273, 0.4491]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
